### ISSUE TITLE
Tie points (help)

### ISSUE THREAD

**Issue by Weixing-Zhang** [GFZ/arosics#10]
* arosics version: 1.7.6
* Python version: 3.9
* Operating System: macOS Monterey
### Description

I was trying to extract the final tie point by using the global approach - [CoReg](https://github.com/GFZ/arosics/blob/master/arosics/CoReg.py). According to the workflow chart (Figure 1) of the approach in the paper, I thought that the tie point will be the input for the next step. I wonder how I may be able to export the tie point information. Any help is much appreciated.

![iScreen Shoter - 2022-04-19 15:30:30 868](https://user-images.githubusercontent.com/10710457/164081149-f3fa1909-8adc-4771-b711-363bba70a37c.jpg)

**Comment by danschef** [comment]
Hi @Weixing-Zhang!

In case of the global approach, the tie point is stored internally and used as input for image warping. You can access it like this:

```
CR = COREG('ref.tif', 'tgt.tif') 
CR.calculate_spatial_shifts()
CR.x_shift_map  # x-shift in map units
CR.y_shift_map  # y-shift in map units
CR.x_shift_px  # x-shift in pixels
CR.y_shift_px  # y-shift in pixels
CR.vec_angle_deg  # angle of shift vector in degrees
CR.vec_length_map  # shift vector length in map units
```

Does this help?

**Comment by Weixing-Zhang** [comment]
Hi @danschef,

Understood. That's what I have figured so far. 

My understanding of tie points is that they are the common locations within the overlap areas so they will have x and y for the reference and target images. I thought there is a tie point grid table like the one from the local method. In the current design of the arosics, this information was represented by x- and y-shift so the actual x and y for the reference and target images can be easily derived. That makes sense.

Thank you so much for the confirmation.

**Comment by Weixing-Zhang** [comment]
Using the CR.win_pos_XY and shift values does the job. 

Thank you so much for the explanation. I am closing this help ticket.
