### ISSUE TITLE
reproducibility of processing with RANSAC

### ISSUE THREAD

**Issue by nth29** [GFZ/arosics#18]
* arosics version: 1.8.0
* Python version: 3.9.2
* Operating System: Debian 11.1

### Description

When using Arosics with RANSAC GCP outliers filtering, which is a not deterministic process, for similar input parameters, the final set of GCPs found by COREG_LOCAL is not always the same.

Because tuning Arosics parameters is an iterative process, we are working on a reduced 3 band dataset of an hyperspectral datacubes for this "tunning" step and, once we will have found the good parameters, we would like to apply exactly the same shift to the full hyperspectral cube.

For that, due to RANSAC, keeping the same input parameters is not enough, thus, is there a way  to save COREG_LOCAL GCPs results and parameters, and apply them afterward using DESHIFTER for example ?

**Comment by danschef** [comment]
arosics version 1.9.0 now uses a fixed random_state by default when calling RANSAC (implemented [here](https://git.gfz-potsdam.de/danschef/arosics/-/merge_requests/35)). This ensures reproducable results from the RANSAC outlier filtering and should therefore fix this issue.
