### ISSUE TITLE
Arosics for Pleiades satellite 

### ISSUE THREAD

**Issue by czarnes22** [GFZ/arosics#34]
* arosics version: 1.10.1
* Python version: python 3
* Operating System: win10

Dear Daniel,
Forgive me for asking this, however, I have a basic familiarity with your software and the Python language. Of course I understand most of the concepts i.e. mapping system, geotiff, etc. however, going through the coregistration of two satellite images is beyond me. Would you be able to create a tutorial, a short instructional video, where you show how you enter the data, how it is processed and what the result of this action looks like? 
I would like to add that I have images from Pleiades satellite and I would like to process them into a form corresponding to Landsat or Sentinel program images, but it keeps displaying me errors. Probably I am doing a certain step incorrectly, but it is such walking in the fog in this case.
Pleiades has a complex structure of images, so choosing the right information, path, etc. is complicated for me
Please consider this request positively, perhaps it will help not only me, but most of those interested.

I wish you a nice day,
Kamil

**Comment by danschef** [comment]
At the moment, I don´t have the time to create tutorial videos, sorry. Please refer to the [usage instructions in the documentation](https://danschef.git-pages.gfz-potsdam.de/arosics/doc/usage.html) and you should be good to go.

If you run into errors that you cannot resolve with the documentation, feel free to open an issue here that describes the error, your input data and how you called AROSICS.
