### ISSUE TITLE
Landsat products projection problem in southern hemisphere

### ISSUE THREAD

**Issue by shahriar49** [GFZ/arosics#6]
* arosics version: Any
* Python version: Any
* Operating System: Any

### Description
I tried to co-register a Landsat-8 collection-2 level-2 surface reflectance image to a Sentinel-2 MSI level-2 image, both taken in South Africa via Google Earth Engine. But I got this error:

`RuntimeError: Input projections are not equal. Different projections are currently not supported. Got WGS 84 / UTM zone 36S vs. WGS 84 / UTM zone 36N.
`

I found that while GEE Sentinel-2 products have proper UTM zone designation for northern or southern hemisphere, the GEE Landsat-8 collection surface reflectance products are all designated by UTM north projections even if the scene is for the southern hemisphere (see https://gis.stackexchange.com/questions/269004/wrong-projection-from-landsat-8-surface-reflectance-collection-in-gee). Although they modified the false_northing parameter to place the image correctly on display, but it makes the AROSICS program to fault.

P.S. I checked Landsat 8 TOA products and it had the same problem.

**Comment by danschef** [comment]
Well, the only thing I could do here is to somehow read the false-northing parameter to correct for the hemisphere. But I have to check if that makes sense and can be implemented robustly.

The output of `gdalinfo /path/to/file/with/wrong/hemishere` might help with that.
