### ISSUE TITLE
Minor issue in documentation

### ISSUE THREAD

**Issue by tdollenb** [GFZ/arosics#7]
The documentation for the arosics.CoReg module is currently inconsistent. The default value for the parameter `force_quadratic_win` and `binary_ws` of type `bool` is documented with `1` while all other `bool` type parameters have either `True` or `False` as default values.
This also does not match the class constructor.

**Comment by danschef** [comment]
Thanks for reporting, this will be fixed soon.

**Comment by danschef** [comment]
This is fixed in v1.7.2: https://github.com/GFZ/arosics/blob/master/HISTORY.rst#172-2021-11-09.
